name: Daily tasks

on:
  schedule:
    - cron: 0 16 * * *  # timezone: UTC
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
            then pip install -r requirements.txt;
          fi

      - name: Run scripts
        run: |
          python src/check_in/script.py
          python src/lottery/script.py
        env:
          PYTHONPATH: src/
          JUEJIN_SESSION_ID: ${{ secrets.JUEJIN_NUM_SESSION_ID }}
